module.exports = [ 
  { 
    teamName: 'Man City',
    played: 30,
    won: 26,
    draw: 3,
    lost: 1,
    for: 85,
    against: 20,
    points: 81,
    form: ['D','W','W','W','W'],
    goal_difference: 65,
    key: 'MCI' 
  }, { 
    teamName: 'Man Utd',
    played: 30,
    won: 20,
    draw: 5,
    lost: 5,
    for: 58,
    against: 23,
    points: 65,
    form:  ['W','L','W','W','W'],
    goal_difference: 35,
    key: 'MUN' },
  { teamName: 'Liverpool',
    played: 31,
    won: 18,
    draw: 9,
    lost: 4,
    for: 73,
    against: 34,
    points: 63,
    form:  ['W','W','W','L','W'],
    goal_difference: 39,
    key: 'LIV' },
  { teamName: 'Spurs',
    played: 30,
    won: 18,
    draw: 7,
    lost: 5,
    for: 59,
    against: 25,
    points: 61,
    form:  ['D','W','W','W','W'],
    goal_difference: 34,
    key: 'TOT' },
  { teamName: 'Chelsea',
    played: 30,
    won: 17,
    draw: 5,
    lost: 8,
    for: 52,
    against: 27,
    points: 56,
    form:  ['L','W','L','L','W'],
    goal_difference: 25,
    key: 'CHE' },
  { teamName: 'Arsenal',
    played: 30,
    won: 14,
    draw: 6,
    lost: 10,
    for: 55,
    against: 41,
    points: 48,
    form:  ['W','L','L','L','W'],
    goal_difference: 14,
    key: 'ARS' },
  { teamName: 'Burnley',
    played: 30,
    won: 11,
    draw: 10,
    lost: 9,
    for: 27,
    against: 26,
    points: 43,
    form:  ['D','L','D','W','W'],
    goal_difference: 1,
    key: 'BUR' },
  { teamName: 'Leicester',
    played: 30,
    won: 10,
    draw: 10,
    lost: 10,
    for: 45,
    against: 43,
    points: 40,
    form:  ['D','L','D','D','W'],
    goal_difference: 2,
    key: 'LEI' },
  { teamName: 'Everton',
    played: 31,
    won: 11,
    draw: 7,
    lost: 13,
    for: 37,
    against: 50,
    points: 40,
    form:  ['W','L','L','W','W'],
    goal_difference: -13,
    key: 'EVE' },
  { teamName: 'Bournemouth',
    played: 31,
    won: 9,
    draw: 9,
    lost: 13,
    for: 37,
    against: 49,
    points: 36,
    form:  ['L','D','D','L','W'],
    goal_difference: -12,
    key: 'BOU' },
  { teamName: 'Watford',
    played: 31,
    won: 10,
    draw: 6,
    lost: 15,
    for: 39,
    against: 55,
    points: 36,
    form:  ['L','W','W','L','L'],
    goal_difference: -16,
    key: 'WAT' },
  { teamName: 'Brighton',
    played: 30,
    won: 8,
    draw: 10,
    lost: 12,
    for: 28,
    against: 40,
    points: 34,
    form:  ['W','D','W','W','L'],
    goal_difference: -12,
    key: 'BHA' },
  { teamName: 'Newcastle',
    played: 30,
    won: 8,
    draw: 8,
    lost: 14,
    for: 30,
    against: 40,
    points: 32,
    form:  ['D','W','D','L','W'],
    goal_difference: -10,
    key: 'NEW' },
  { teamName: 'Swansea',
    played: 30,
    won: 8,
    draw: 7,
    lost: 15,
    for: 25,
    against: 42,
    points: 31,
    form:  ['D','W','L','W','D'],
    goal_difference: -17,
    key: 'SWA' },
  { teamName: 'Huddersfield',
    played: 31,
    won: 8,
    draw: 7,
    lost: 16,
    for: 25,
    against: 52,
    points: 31,
    form:  ['W','W','L','D','L'],
    goal_difference: -27,
    key: 'HUD' },
  { teamName: 'Crystal Palace',
    played: 31,
    won: 7,
    draw: 9,
    lost: 15,
    for: 30,
    against: 48,
    points: 30,
    form:  ['L','L','L','L','W'],
    goal_difference: -18,
    key: 'CRY' },
  { teamName: 'West Ham',
    played: 30,
    won: 7,
    draw: 9,
    lost: 14,
    for: 36,
    against: 57,
    points: 30,
    form:  ['L','W','L','L','L'],
    goal_difference: -21,
    key: 'WHU' },
  { teamName: 'Southampton',
    played: 30,
    won: 5,
    draw: 13,
    lost: 12,
    for: 29,
    against: 44,
    points: 28,
    form:  ['W','L','D','D','L'],
    goal_difference: -15,
    key: 'SOU' 
  }, { 
    teamName: 'Stoke',
    played: 31,
    won: 6,
    draw: 9,
    lost: 16,
    for: 29,
    against: 58,
    points: 27,
    form:  ['D','D','D','L','L'],
    goal_difference: -29,
    key: 'STK' 
  }, { 
    teamName: 'West Brom',
    played: 31,
    won: 3,
    draw: 11,
    lost: 17,
    for: 24,
    against: 49,
    points: 20,
    form:  ['L','L','L','L','L'],
    goal_difference: -25,
    key: 'WBA' 
  } 
];